/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import modelo.negocion.*;

/**
 *
 * @author David Torrez
 */
public class Vdisciplina extends javax.swing.JFrame {

    /**
     * Creates new form Vcliente
     */
    Ndisciplina nDisciplina;
    Ninstructor nInstructor;
    Nsala nSala;


    public Vdisciplina() {
        initComponents();
        this.setLocationRelativeTo(null);

        nDisciplina = new Ndisciplina();
        nInstructor = new Ninstructor();
        nSala = new Nsala();
        this.getDisciplinas();
        this.getComboBoxs();
        this.hideShowId(false);
    }

    public void getDisciplinas() {
        this.jtableDisciplina.setModel(nDisciplina.getTablaDisciplinas(0));

    }

    public void limpiar() {
        this.jtextId.setText("");
        this.jtextNombre.setText("");
        this.jtextDescripcion.setText("");
        this.jcbxInstructor.setSelectedIndex(0);
        this.jcbxSala.setSelectedIndex(0);
        jchbx1.setSelected(false);
        jchbx2.setSelected(false);
        jchbx3.setSelected(false);
        jchbx4.setSelected(false);
    }

    public void getComboBoxs() {
        System.out.println("ComboBox");
        DefaultComboBoxModel comboBox = this.nInstructor.getComboBoxInstructores();
        jcbxInstructor.setModel(comboBox);

        comboBox = this.nSala.getComboBoxSalas();
        jcbxSala.setModel(comboBox);

    }

    public ArrayList<String> getHorariosChecked() {
        ArrayList<String> horario = new ArrayList<>();

        if (jchbx1.isSelected()) {
            horario.add(jchbx1.getText().trim());
        }
        if (jchbx2.isSelected()) {
            horario.add(jchbx2.getText().trim());
        }
        if (jchbx3.isSelected()) {
            horario.add(jchbx3.getText().trim());
        }
        if (jchbx4.isSelected()) {
            horario.add(jchbx4.getText().trim());
        }
        return horario;
    }

    private void selectedComboBox(String instructor, String sala) {
        int cant1 = jcbxInstructor.getItemCount();
        int cant2 = jcbxSala.getItemCount();
        for (int i = 1; i < cant1; i++) {
            jcbxInstructor.setSelectedIndex(i);
            Ninstructor instructorSelected = (Ninstructor) jcbxInstructor.getSelectedItem();
            if (instructorSelected.getNombre().equals(instructor)) {
                break;
            }
        }
        for (int i = 1; i < cant2; i++) {
            jcbxSala.setSelectedIndex(i);
            Nsala salaSelected = (Nsala) jcbxSala.getSelectedItem();
            if (salaSelected.getNombre().equals(sala)) {
                break;
            }
        }

    }

    public void cargarHorarios(ArrayList<String> list) {
        
        for (String nhorario : list) {
            System.out.println(nhorario);
            if (jchbx1.getText().equals(nhorario)) {
                jchbx1.setSelected(true);
            }
            if (jchbx2.getText().equals(nhorario)) {
                jchbx2.setSelected(true);
            }
            if (jchbx3.getText().equals(nhorario)) {
                jchbx3.setSelected(true);
            }
            if (jchbx4.getText().equals(nhorario)) {
                jchbx4.setSelected(true);
            }
        }
    }

    public void hideShowId(boolean bandera) {
        jlbId.setVisible(bandera);
        jtextId.setVisible(bandera);
    }

    public JComboBox getJcbxInstructores() {
        return jcbxInstructor;
    }

    public JComboBox getJcbxSalas() {
        return jcbxSala;
    }

    public JTextField getJtextId() {
        return jtextId;
    }

    public JTextField getJtextDescripcion() {
        return jtextDescripcion;
    }

    public JTextField getJtextNombre() {
        return jtextNombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jlbId = new javax.swing.JLabel();
        jtextId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtextNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableDisciplina = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtextDescripcion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcbxInstructor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcbxSala = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jchbx1 = new javax.swing.JCheckBox();
        jchbx2 = new javax.swing.JCheckBox();
        jchbx3 = new javax.swing.JCheckBox();
        jchbx4 = new javax.swing.JCheckBox();
        btnMain = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbId.setText("Nro");

        jtextId.setEditable(false);
        jtextId.setFocusable(false);

        jLabel2.setText("Nombre");

        jtextNombre.setText("SA-1");

        jtableDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro", "Nombre", "Instructor", "Sala", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableDisciplina);

        jLabel3.setText("Descripción");

        jtextDescripcion.setText("Descripxión cualquiera.");

        btnRegistrar.setText("Registrar");

        btnModificar.setText("Modificar");

        btnEliminar.setText("Eliminar");

        jLabel7.setText("Lista de Disciplinas");

        jLabel1.setText("Instructor");

        jcbxInstructor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Sala");

        jcbxSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Horarios");

        jchbx1.setText("Lun-Vie. 8:00am-21:00pm");

        jchbx2.setText("Sab. 8:00am-20:00pm");

        jchbx3.setText("Lun-Mie-Vie. 8:00am-12:00pm");

        jchbx4.setText("Mar-Jue. 8:00am-12:00pm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchbx1)
                    .addComponent(jchbx2)
                    .addComponent(jchbx3)
                    .addComponent(jchbx4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jchbx1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchbx2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchbx3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchbx4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMain.setText("Main");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnMain))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel7)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addGap(4, 4, 4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbxInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jcbxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(95, 95, 95))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtextId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(19, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbId)
                    .addComponent(jtextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxInstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jcbxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnMain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Vdisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Vdisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Vdisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Vdisciplina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Vdisciplina().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnMain;
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbxInstructor;
    private javax.swing.JComboBox<String> jcbxSala;
    private javax.swing.JCheckBox jchbx1;
    private javax.swing.JCheckBox jchbx2;
    private javax.swing.JCheckBox jchbx3;
    private javax.swing.JCheckBox jchbx4;
    private javax.swing.JLabel jlbId;
    public javax.swing.JTable jtableDisciplina;
    private javax.swing.JTextField jtextDescripcion;
    private javax.swing.JTextField jtextId;
    private javax.swing.JTextField jtextNombre;
    // End of variables declaration//GEN-END:variables

    public void cargarCampos(Map<String, String> datos) {
        Map<String, String> instructor = nInstructor.getInstructor(datos.get("id_instructor"), 1);
        Map<String, String> sala = nSala.getSala(Integer.parseInt(datos.get("id_sala")));
        this.selectedComboBox(instructor.get("nombre"), sala.get("nombre"));
        this.hideShowId(true);
        jtextId.setText(datos.get("id"));
        jtextNombre.setText(datos.get("nombre"));
        jtextDescripcion.setText(datos.get("descripcion"));
    }
}
